### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by SadeghHayeri** [amerireza/persianpodcasts#3]
فایل اکسلش رو بیار توی همون ریدمیش،‌ اینجوری هم راحت‌تره دسترسیش و هم نیاز نیست یچیزی داشته باشی که اکسل باز کنه!

**Comment by amerireza** [comment]
دقیق متوجه نشدم!

**Comment by SadeghHayeri** [comment]
https://github.com/petermbenjamin/awesome-podcasts
این شکلی مثلا
